# Aliases
alias grep='grep --color=auto'
alias ll='gls -lah --color=auto --group-directories-first'
alias du='gdu -Phc -d 1'
alias dusort='gdu -Phc -d 1 | sort -h'
alias df='gdf -Th'
alias mc='mc -b'
alias mkdir='mkdir -pv'
alias myip="curl http://ip-api.com/line; echo"
alias passwords='gpg --decrypt ~/passwords.gpg | less'
alias passwords_decrypt='gpg --output /tmp/passwords -d ~/passwords.gpg && vim /tmp/passwords'
alias passwords_encrypt='gpg --output ~/passwords.gpg --cipher-algo AES256 --symmetric /tmp/passwords && rm -P /tmp/passwords'
alias vim='nvim'
alias docker_rmi_dangling='docker rmi $(docker images -q -f dangling=true)'
alias screenfetch='screenfetch 2>/dev/null'

# Get linux command cheatsheet from http://cheat.sh/
cheatsh() {
  args="${*:?How to use: cheatsh bash copy with progress bar}"
  query=${args// /+}
  query=${query/+//}
  curl cheat.sh/$query
}

# Prompt
[ -f ~/.bash_prompt ] && . ~/.bash_prompt

# Autocompletion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# The next line updates PATH for the Google Cloud SDK.
[ -f ~/.local/share/google-cloud-sdk/path.bash.inc ] && . ~/.local/share/google-cloud-sdk/path.bash.inc

# The next line enables shell command completion for gcloud.
[ -f ~/.local/share/google-cloud-sdk/completion.bash.inc ] && . ~/.local/share/google-cloud-sdk/completion.bash.inc

# The next line update PATH for the Istio
[ -d ~/.local/share/istio/bin ] && export PATH="~/.local/share/istio/bin:$PATH"

# Configure nvm (Node.js version manager)
export NVM_DIR="$HOME/.nvm"
[ -f "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -f "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

