# Apply Tokyonight colorschema
source-file ~/.config/tmux/tmux.tokyonight.conf

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g default-terminal xterm-256color
set -g default-shell /bin/zsh
set -sg escape-time 0

# Start index of window/pane with 1, because we're humans, not computers
set -g base-index 1
setw -g pane-base-index 1
# Keep the window number "gapless"
set -g renumber-windows on

# Always show the status bar
set -g status on
set -g status-position top
set -g status-right ""

# Update files on focus (using for vim)
set -g focus-events on

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Enable vim keybindings
set -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# I know it's conterintuitive but for me that works better 
# as the "p" key at the right side of the "n" key. That is aligned better with
# the direction of the "next" and "previous" selection, from left to right.
bind p next-window
bind n previous-window

# For preview in yazi and nnn
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# Make the active pane border bright
set -g pane-active-border-style "fg=colour24"

# List of plugins
# prefix + I (install)
# prefix + U (update)
# prefix + alt + u (uninstall)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark' # or 'light'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# Override gruvbox colors
# set -g pane-active-border-style bg=default,fg=#2e2e2e
# set -g pane-border-style fg=#2e2e2e
