set nocompatible

call plug#begin('~/.vim/plugged')

" Theme
Plug 'morhetz/gruvbox'

" Explore
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'jlanzarotta/bufexplorer'
Plug 'vim-airline/vim-airline'
" Plug 'Shougo/denite.nvim'

" Editor
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-fugitive'
Plug 'ervandew/supertab'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

" Checker
Plug 'w0rp/ale'

" JS
Plug 'pangloss/vim-javascript'
Plug 'maxmellon/vim-jsx-pretty'

" TypeScript
Plug 'HerringtonDarkholme/yats.vim'

" CSS in JS
" Plug 'styled-components/vim-styled-components', { 'branch': 'main' }
"
" CSS
" Plug 'hail2u/vim-css3-syntax'
Plug 'ap/vim-css-color'

" GraphQL
Plug 'jparise/vim-graphql'

" Snippets
Plug 'SirVer/ultisnips'
Plug 'https://github.com/EddiG/vim-snippets.git'

" Cheat sheets
" Accessable via <leader>KB or <leader>KK
Plug 'dbeniamine/cheat.sh-vim'

call plug#end()

syntax on

" Set the leader key
let mapleader = ","
noremap \ ,

" Theme
let g:gruvbox_italic = 1
set background=dark
colorscheme gruvbox

" Allow switching from not saved buffer
set hidden

" Ask confirmation if there is not saved buffer and I'm trying to quit from vim
set confirm

" Don't redraw while executing macros (good performance config)
set lazyredraw

" Ignore letter case in search pattern
set ignorecase

" Honor letter case if the pattern contains uppercase letters
set smartcase

" Show suggestions in the command pallete
set wildmenu

" Highlighting the search result
set hlsearch

" Show line number
set number

" Turn off unnecessary backups
set nobackup
set noswapfile
set nowb

set autoindent
set expandtab
set softtabstop=2
set shiftwidth=2
set tabstop=2

" This will cause Vim to treat all numerals as decimal,
" regardless of whether they are padded with zeros.
set nrformats=

" Allow per-project configuration
set exrc
set secure

" Map <Esc> to exit terminal-mode:
tnoremap <Esc> <C-\><C-n>

" Paste with placing the replaced content in 'the black hole register'
vnoremap p "_dP

" ================ Persistent Undo ==================
" Keep undo history across sessions, by storing in file.
if has('persistent_undo')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" ================ Linting & Formatting ==================
" ALE (Asynchronus Lint Engine)
" Use these configuration options per project
"
" let g:ale_linters = {}
" let g:ale_linters['javascript'] = ['eslint']
" let g:ale_javascript_eslint_use_global = 0
" let g:ale_javascript_eslint_suppress_missing_config = 1
" let g:ale_javascript_eslint_suppress_eslintignore = 1

let g:ale_fixers = {}
let g:ale_fixers['javascript'] = ['prettier']
let g:ale_fixers['json'] = ['prettier']
let g:ale_fixers['css'] = ['prettier']
" let g:ale_javascript_prettier_use_local_config = 1
" let g:ale_fix_on_save = 1

" Completion
" let g:ale_completion_enabled = 1
" autocmd FileType typescript call deoplete#disable()
" autocmd FileType typescript setlocal omnifunc=ale#completion#OmniFunc

nnoremap <silent> <Leader>d :ALEGoToDefinition<CR>
nnoremap <silent> <Leader>r :ALEFindReferences<CR>
" ========================================================

" For pangloss/vim-javascript plugin (enable Flow syntax)
" let g:javascript_plugin_flow = 1

" Deoplete (autocomplete)
let g:deoplete#enable_at_startup=1
let g:deoplete#enable_ignore_case=1

" NERDTree
nmap <C-\> :NERDTreeFind<CR>
nmap <silent> <leader><leader> :NERDTreeToggle<CR>

" Ctrlp
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline#extensions#tabline#buffer_nr_show = 1
set laststatus=2

" Bufexplorer
let g:bufExplorerDisableDefaultKeyMapping = 1
let g:bufExplorerDetailedHelp = 1
let g:bufExplorerShowRelativePath = 1
let g:bufExplorerShowTabBuffer = 1
let g:bufExplorerSortBy = 'fullpath'
let g:bufExplorerSplitBelow = 1
let g:bufExplorerSplitRight = 1
let g:bufExplorerSplitOutPathName = 0
nnoremap <leader>b :BufExplorer<CR>
nnoremap <Leader>l :ls<CR>
nnoremap <Leader>g :e#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

" Supertab
let g:SuperTabMappingForward='<s-tab>'
let g:SuperTabMappingBackward='<tab>'

" Map ctrl-movement keys to window switching
nmap <silent> <C-k> <C-w><Up>
nmap <silent> <C-j> <C-w><Down>
nmap <silent> <C-l> <C-w><Right>
nmap <silent> <C-h> <C-w><Left>

" Map keys for window resizing
nmap <silent> <C-n> <C-w><
nmap <silent> - <C-w>-
nmap <silent> = <C-w>+
nmap <silent> <C-m> <C-w>>

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Define files that have json format
autocmd BufRead,BufNewFile .babelrc,.eslintrc,.prettierrc set filetype=json

" Trigger configuration (Optional)
let g:UltiSnipsExpandTrigger="<C-l>"
