# This file runs once when the login shell starts. The result will be shared with the other non-login shells.

# Configure brew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Configure zoxide
# brew install zoxide
eval "$(zoxide init --cmd j zsh)"

