# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/Users/eddig/.local/bin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

# JS package manager
export PNPM_HOME="/Users/eddig/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# Configure Ruby environment manager
eval "$(rbenv init - zsh)"

# bun completions
[ -s "/Users/eddig/.bun/_bun" ] && source "/Users/eddig/.bun/_bun"
# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Add the SSH identity files to the ssh-agent
# ssh-add --apple-load-keychain
# Run that command only once at the system startup time by adding a launch agent
# https://unix.stackexchange.com/a/560404

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias vim='nvim'
alias top='btop'
alias ll='lsd -lah --group-dirs first'
alias du='dua i'
alias dig='doggo'
alias mkdir='mkdir -pv'
alias myip="curl http://ip-api.com/line; echo"
alias passwords='pass show all | less; clear && tmux clear-history'
alias passwords_edit='EDITOR="vim --clean" pass edit all; clear && tmux clear-history'
# alias passwords='gpg --decrypt ~/.passwords | less'
# alias passwords_decrypt='gpg --output /tmp/.passwords -d ~/.passwords && vim /tmp/.passwords'
# alias passwords_encrypt='gpg --output ~/.passwords --cipher-algo AES256 --symmetric /tmp/.passwords && rm -P /tmp/.passwords'
alias docker_rmi_dangling='docker rmi $(docker images -q -f dangling=true)'
alias screenfetch='neofetch'
alias cpsafe='rsync -av --progress --exclude node_modules --exclude .git'
alias pn='pnpm'
alias pnx='pnpx'
alias lg='lazygit'
alias gs='git status'
alias mykill='pkill nvim prettierd eslintd rust-analyzer node'
alias cc='cd ~/.claude-chat && claude'
alias c='claude'
alias glow='glow -w 120'
alias y='yazi'

# This works with both the shell input redirection and the pipelines
# 1. jqless < data.json
# 2. cat data.json | jqless
jqless() {
    jq -C "$@" | less -R
}

# Fuzzy searcher files (fzf + ripgrep)
# brew install fzf ripgrep
# export FZF_DEFAULT_COMMAND='rg --files --follow --hidden'
# brew install fzf fd
export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git --exclude node_modules'
alias fzfp="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' | xargs -I {} nvim {}"
alias fzf="fzf --bind 'enter:execute($EDITOR {})'"

# Get linux command cheatsheet from http://cheat.sh/
# Usage: cheatsh curl
cheatsh() {
  args="${*:?How to use: cheatsh bash copy with progress bar}"
  query=${args// /+}
  query=${query/+//}
  curl cheat.sh/$query
}

# Retreive information about provided domain.
# Usage: domain_lookup google.com
domain_lookup() {
  local domain="$1"

  if [ -z "$domain" ]; then
    echo "Usage: domain_lookup <domain>"
    return 1
  fi

  local ip_address=$(/usr/bin/dig @1.1.1.1 +short "$domain" A | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)

  if [ -z "$ip_address" ]; then
    echo "$domain: Could not resolve"
    return
  fi

  local asn_info=$(/usr/bin/whois -h whois.cymru.com " -v $ip_address" 2>/dev/null | tail -n1)

  if [ -n "$asn_info" ]; then
    local asn=$(echo "$asn_info" | awk '{print $1}')
    local country=$(echo "$asn_info" | cut -d'|' -f4 | xargs)
    local owner=$(echo "$asn_info" | cut -d'|' -f5- | xargs)

    if [ -n "$asn" ] && [ "$asn" != "NA" ]; then
      echo "$domain: $ip_address | AS$asn | $country | $owner"
    else
      echo "$domain: $ip_address"
    fi
  else
    echo "$domain: $ip_address"
  fi
}

# Setup pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# fnm
eval "$(fnm env --use-on-cd --corepack-enabled --version-file-strategy recursive --shell zsh)"

# Add docker tool when it was installed only for the current user.
[[ -d $HOME/.docker/bin ]] && export PATH="$HOME/.docker/bin:$PATH"
